export const mockPartners = [
  {
    id: 1,
    name: "Sunshine Travel",
    logo: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    date: "12/03/2023",
    tourCore: "Tour khám phá miền Trung - di sản và biển xanh.",
    benefit: "Tăng 45% lượt khách đặt tour qua nền tảng, nâng cao thương hiệu địa phương.",
    rating: 5,
  },
  {
    id: 2,
    name: "Green Hotel Group",
    logo: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    date: "07/08/2023",
    tourCore: "Chuỗi nghỉ dưỡng xanh kết hợp du lịch sinh thái.",
    benefit: "Nhận hơn 2.000 lượt đặt phòng mới qua các tour tích hợp với website.",
    rating: 5,
  },
  {
    id: 3,
    name: "Ocean Transport",
    logo: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    date: "15/01/2024",
    tourCore: "Dịch vụ vận chuyển khách du lịch biển đảo cao cấp.",
    benefit: "Tăng doanh thu 30% từ khách hàng đặt combo tour và vận chuyển.",
    rating: 5,
  },
  {
    id: 4,
    name: "Mountain Adventure Co.",
    logo: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e",
    date: "02/06/2024",
    tourCore: "Tour leo núi kết hợp cắm trại - hướng đến du lịch mạo hiểm bền vững.",
    benefit: "Website giúp quảng bá dịch vụ đến nhóm khách quốc tế nhanh chóng hơn.",
    rating: 5,
  },
];
